# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1J11WqFixDAKZ6qRmxUlWYErQodzWP3r5
"""

def get_radius(prompt):
    r = int(input(prompt))  # 입력받은 값을 정수로 변환
    return r

def get_circle_area(radius):
    return 3.14 * radius * radius  # 원의 넓이 계산 (πr²)

# 실행 부분
radius = get_radius("넓이를 구하고자 하는 원의 반지름은? ")  # 사용자 입력
area = get_circle_area(radius)  # 원의 넓이 계산

print(f"반지름 {radius}인 원의 넓이 = 3.14 x {radius} x {radius} = {area}")  # 결과 출력