Python 3.13.2 (tags/v3.13.2:4f8bb39, Feb  4 2025, 15:23:48) [MSC v.1942 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license()" for more information.
>>> def get_fixed_price(discount_rate, discounted_price):
...     original_price = discounted_price / (1 - discount_rate / 100)
...     return round(original_price)
... 
... 
... discount = float(input("할인율은? "))
... a_discounted = int(input("A 상품의 할인된 가격은? "))
... b_discounted = int(input("B 상품의 할인된 가격은? "))
... 
... 
... a_original = get_fixed_price(discount, a_discounted)
... b_original = get_fixed_price(discount, b_discounted)
... 
... 
... print(f"A 상품의 정가는 {a_original} 원")
... print(f"B 상품의 정가는 {b_original} 원")
